=== AurionProject/Aurion/Product/SoapUI_Test/PerformanceSuite/soapui-project-conf.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="tests" xmlns="http://www.agilex.com/schemas/soapUICustom.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="tests">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element name="test">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="testProperties" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="property" nillable="true" minOccurs="1" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="name" type="xs:string" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="deleteOnExit" type="xs:string"/>
                  <xs:attribute name="filename" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="testcase" type="xs:string" use="required" />
            <xs:attribute name="numberOfIteration" type="xs:string" use="required" />
            <xs:attribute name="numberOfThreads" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AurionProject/Aurion/Product/SoapUI_Test/PerformanceSuite/DocRetrieveLoadTest-soapui-project-conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="soapui-project-conf.xsd">
  <test name="DocRetrieve-OneDocument(1tx1r)" testcase="Nhin.DocRetrieve.SingleDocument" numberOfThreads="1" numberOfIteration="1">
    <testProperties filename="DocRetrieveLoadTest-soapui-project.properties">
      <property name="DocRetrieve.HomeCommunityId">${#Project#Endpoint-HomeCommunityId}</property>  
      <property name="DocRetrieve.RepositoryId">1</property>
      <property name="DocRetrieve.DocumentId">1.123402.11111</property>
      <property name="DocRetrieve.ExpectedSizeOfDocuments">35000</property>
    </testProperties>
  </test>

  <test name="DocRetrieve-OneDocument(1tx50r)" testcase="Nhin.DocRetrieve.SingleDocument" numberOfThreads="1" numberOfIteration="50">
    <testProperties filename="DocRetrieveLoadTest-soapui-project.properties">
      <property name="DocRetrieve.HomeCommunityId">${#Project#Endpoint-HomeCommunityId}</property>  
      <property name="DocRetrieve.RepositoryId">1</property>
      <property name="DocRetrieve.DocumentId">1.123402.11111</property>
      <property name="DocRetrieve.ExpectedSizeOfDocuments">35000</property>
    </testProperties>
  </test>
  <test name="DocRetrieve-OneDocument(2tx50r)" testcase="Nhin.DocRetrieve.SingleDocument" numberOfThreads="2" numberOfIteration="50">
    <testProperties filename="DocRetrieveLoadTest-soapui-project.properties">
      <property name="DocRetrieve.HomeCommunityId">${#Project#Endpoint-HomeCommunityId}</property>  
      <property name="DocRetrieve.RepositoryId">1</property>
      <property name="DocRetrieve.DocumentId">1.123402.11111</property>
      <property name="DocRetrieve.ExpectedSizeOfDocuments">35000</property>
    </testProperties>
  </test>
  <test name="DocRetrieve-OneDocument(5tx50r)" testcase="Nhin.DocRetrieve.SingleDocument" numberOfThreads="5" numberOfIteration="50">
    <testProperties filename="DocRetrieveLoadTest-soapui-project.properties">
      <property name="DocRetrieve.HomeCommunityId">${#Project#Endpoint-HomeCommunityId}</property>  
      <property name="DocRetrieve.RepositoryId">1</property>
      <property name="DocRetrieve.DocumentId">1.123402.11111</property>
      <property name="DocRetrieve.ExpectedSizeOfDocuments">35000</property>
    </testProperties>
  </test>
  <test name="DocRetrieve-OneDocument(10tx50r)" testcase="Nhin.DocRetrieve.SingleDocument" numberOfThreads="10" numberOfIteration="50">
    <testProperties filename="DocRetrieveLoadTest-soapui-project.properties">
      <property name="DocRetrieve.HomeCommunityId">${#Project#Endpoint-HomeCommunityId}</property>  
      <property name="DocRetrieve.RepositoryId">1</property>
      <property name="DocRetrieve.DocumentId">1.123402.11111</property>
      <property name="DocRetrieve.ExpectedSizeOfDocuments">35000</property>
    </testProperties>
  </test>
  <test name="DocRetrieve-OneDocument(25tx50r)" testcase="Nhin.DocRetrieve.SingleDocument" numberOfThreads="25" numberOfIteration="50">
    <testProperties filename="DocRetrieveLoadTest-soapui-project.properties">
      <property name="DocRetrieve.HomeCommunityId">${#Project#Endpoint-HomeCommunityId}</property>  
      <property name="DocRetrieve.RepositoryId">1</property>
      <property name="DocRetrieve.DocumentId">1.123402.11111</property>
      <property name="DocRetrieve.ExpectedSizeOfDocuments">35000</property>
    </testProperties>
  </test>

  <test name="DocRetrieve-OneDocument(1tx1000r)" testcase="Nhin.DocRetrieve.SingleDocument" numberOfThreads="1" numberOfIteration="1000">
    <testProperties filename="DocRetrieveLoadTest-soapui-project.properties">
      <property name="DocRetrieve.HomeCommunityId">${#Project#Endpoint-HomeCommunityId}</property>  
      <property name="DocRetrieve.RepositoryId">1</property>
      <property name="DocRetrieve.DocumentId">1.123402.11111</property>
      <property name="DocRetrieve.ExpectedSizeOfDocuments">35000</property>
    </testProperties>
  </test>
  <test name="DocRetrieve-NoDocument(1tx1000r)" testcase="Nhin.DocRetrieve.SingleDocument" numberOfThreads="1" numberOfIteration="1000">
    <testProperties filename="DocRetrieveLoadTest-soapui-project.properties">
      <property name="DocRetrieve.HomeCommunityId">${#Project#Endpoint-HomeCommunityId}</property>  
      <property name="DocRetrieve.RepositoryId">1</property>
      <property name="DocRetrieve.DocumentId">x</property>
    </testProperties>
  </test>

  <test name="DocRetrieve-SequentialRequestsForMultipleDocuments(1tx50r)" testcase="Nhin.DocRetrieve.SequentialRequestsForMultipleDocuments" numberOfThreads="1" numberOfIteration="20">
    <testProperties filename="DocRetrieveLoadTest-soapui-project.properties">
      <property name="DocRetrieve.HomeCommunityId">${#Project#Endpoint-HomeCommunityId}</property>  
      <property name="DocRetrieve.RepositoryId">1</property>
      <property name="DocRetrieve.DocumentId-1">1.123409.44444</property>
      <property name="DocRetrieve.DocumentId-2">1.123407.11111</property>
      <property name="DocRetrieve.DocumentId-3">1.123407.22222</property>
      <property name="DocRetrieve.DocumentId-4">1.123407.33333</property>
      <property name="DocRetrieve.DocumentId-5">1.123407.44444</property>
    </testProperties>
  </test>

</tests>

=== AurionProject/Aurion/Product/SoapUI_Test/PerformanceSuite/example-soapui-project-conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="soapui-project-conf.xsd">
  <test name="DocQueryLoadTest1" testcase="DocQueryLoadTest-1t x 20r" numberOfIteration="1" numberOfThreads="1">
    <testProperties filename="loadtest.properties">
      <property name="propertyname">propertyvalue</property>
      <property name="propertyname">propertyvalue</property>
    </testProperties>
  </test>
  <test name="DocQueryLoadTest2" testcase="DocQueryLoadTest-1t x 20r" numberOfIteration="1" numberOfThreads="1">
    <testProperties filename="loadtest.properties" deleteOnExit="true">
      <property name="propertyname0">propertyvalue0</property>
      <property name="propertyname1">propertyvalue1</property>
      <property name="propertyname2">propertyvalue2</property>
      <property name="propertyname3">propertyvalue3</property>
    </testProperties>
  </test>
  <test name="DocQueryLoadTest3" testcase="DocQueryLoadTest-1t x 20r" numberOfIteration="1" numberOfThreads="1">
    <testProperties filename="loadtest.properties">
      <property name="property.name0">property.value0</property>
      <property name="property.name1">property.value1</property>
      <property name="property.name2">property.value2</property>
      <property name="property.name3">property.value3</property>
    </testProperties>
  </test>
</tests>

=== AurionProject/Aurion/Product/SoapUI_Test/PerformanceSuite/PatientDiscoveryLoadtest-soapui-project-conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="soapui-project-conf.xsd">
  <!-- 1 Result -->
  <test name="PatientDiscovery(1tx1r)" testcase="Nhin.PatientDiscovery" numberOfThreads="1" numberOfIteration="1">
    <testProperties filename="PatientDiscoveryLoadtest-soapui-project.properties">
      <property name="PatientDiscovery.Patient.GivenName">GALLOW</property>
      <property name="PatientDiscovery.Patient.FamilyName">YOUNGER</property>
      <property name="PatientDiscovery.ExpectedResultCount">1</property>
    </testProperties>
  </test>
  <test name="PatientDiscovery(1tx50r)" testcase="Nhin.PatientDiscovery" numberOfThreads="1" numberOfIteration="50">
    <testProperties filename="PatientDiscoveryLoadtest-soapui-project.properties">
      <property name="PatientDiscovery.Patient.GivenName">GALLOW</property>
      <property name="PatientDiscovery.Patient.FamilyName">YOUNGER</property>
      <property name="PatientDiscovery.ExpectedResultCount">1</property>
    </testProperties>
  </test>
  <test name="PatientDiscovery(1tx100r)" testcase="Nhin.PatientDiscovery" numberOfThreads="1" numberOfIteration="100">
    <testProperties filename="PatientDiscoveryLoadtest-soapui-project.properties">
      <property name="PatientDiscovery.Patient.GivenName">GALLOW</property>
      <property name="PatientDiscovery.Patient.FamilyName">YOUNGER</property>
      <property name="PatientDiscovery.ExpectedResultCount">1</property>
    </testProperties>
  </test>
  <test name="PatientDiscovery(1tx10r)" testcase="Nhin.PatientDiscovery" numberOfThreads="1" numberOfIteration="10">
    <testProperties filename="PatientDiscoveryLoadtest-soapui-project.properties">
      <property name="PatientDiscovery.Patient.GivenName">GALLOW</property>
      <property name="PatientDiscovery.Patient.FamilyName">YOUNGER</property>
      <property name="PatientDiscovery.ExpectedResultCount">1</property>
    </testProperties>
  </test>
  <test name="PatientDiscovery(2tx10r)" testcase="Nhin.PatientDiscovery" numberOfThreads="2" numberOfIteration="10">
    <testProperties filename="PatientDiscoveryLoadtest-soapui-project.properties">
      <property name="PatientDiscovery.Patient.GivenName">GALLOW</property>
      <property name="PatientDiscovery.Patient.FamilyName">YOUNGER</property>
      <property name="PatientDiscovery.ExpectedResultCount">1</property>
    </testProperties>
  </test>
  <test name="PatientDiscovery(10tx10r)" testcase="Nhin.PatientDiscovery" numberOfThreads="10" numberOfIteration="10">
    <testProperties filename="PatientDiscoveryLoadtest-soapui-project.properties">
      <property name="PatientDiscovery.Patient.GivenName">GALLOW</property>
      <property name="PatientDiscovery.Patient.FamilyName">YOUNGER</property>
      <property name="PatientDiscovery.ExpectedResultCount">1</property>
    </testProperties>
  </test>
  <test name="PatientDiscovery(25tx10r)" testcase="Nhin.PatientDiscovery" numberOfThreads="25" numberOfIteration="10">
    <testProperties filename="PatientDiscoveryLoadtest-soapui-project.properties">
      <property name="PatientDiscovery.Patient.GivenName">GALLOW</property>
      <property name="PatientDiscovery.Patient.FamilyName">YOUNGER</property>
      <property name="PatientDiscovery.ExpectedResultCount">1</property>
    </testProperties>
  </test>
  <!-- No Results -->
  <test name="PatientDiscovery-NoResults(1tx1r)" testcase="Nhin.PatientDiscovery" numberOfThreads="1" numberOfIteration="1">
    <testProperties filename="PatientDiscoveryLoadtest-soapui-project.properties">
      <property name="PatientDiscovery.Patient.GivenName">UNKNOWN</property>
      <property name="PatientDiscovery.Patient.FamilyName">UNKNOWN</property>
      <property name="PatientDiscovery.ExpectedResultCount">0</property>
    </testProperties>
  </test>
  <test name="PatientDiscovery-NoResults(1tx50r)" testcase="Nhin.PatientDiscovery" numberOfThreads="1" numberOfIteration="50">
    <testProperties filename="PatientDiscoveryLoadtest-soapui-project.properties">
      <property name="PatientDiscovery.Patient.GivenName">UNKNOWN</property>
      <property name="PatientDiscovery.Patient.FamilyName">UNKNOWN</property>
      <property name="PatientDiscovery.ExpectedResultCount">0</property>
    </testProperties>
  </test>
  <test name="PatientDiscovery-NoResults(1tx100r)" testcase="Nhin.PatientDiscovery" numberOfThreads="1" numberOfIteration="100">
    <testProperties filename="PatientDiscoveryLoadtest-soapui-project.properties">
      <property name="PatientDiscovery.Patient.GivenName">UNKNOWN</property>
      <property name="PatientDiscovery.Patient.FamilyName">UNKNOWN</property>
      <property name="PatientDiscovery.ExpectedResultCount">0</property>
    </testProperties>
  </test>
  <test name="PatientDiscovery-NoResults(1tx10r)" testcase="Nhin.PatientDiscovery" numberOfThreads="1" numberOfIteration="10">
    <testProperties filename="PatientDiscoveryLoadtest-soapui-project.properties">
      <property name="PatientDiscovery.Patient.GivenName">UNKNOWN</property>
      <property name="PatientDiscovery.Patient.FamilyName">UNKNOWN</property>
      <property name="PatientDiscovery.ExpectedResultCount">0</property>
    </testProperties>
  </test>
  <test name="PatientDiscovery-NoResults(2tx10r)" testcase="Nhin.PatientDiscovery" numberOfThreads="2" numberOfIteration="10">
    <testProperties filename="PatientDiscoveryLoadtest-soapui-project.properties">
      <property name="PatientDiscovery.Patient.GivenName">UNKNOWN</property>
      <property name="PatientDiscovery.Patient.FamilyName">UNKNOWN</property>
      <property name="PatientDiscovery.ExpectedResultCount">0</property>
    </testProperties>
  </test>
  <test name="PatientDiscovery-NoResults(10tx10r)" testcase="Nhin.PatientDiscovery" numberOfThreads="10" numberOfIteration="10">
    <testProperties filename="PatientDiscoveryLoadtest-soapui-project.properties">
      <property name="PatientDiscovery.Patient.GivenName">UNKNOWN</property>
      <property name="PatientDiscovery.Patient.FamilyName">UNKNOWN</property>
      <property name="PatientDiscovery.ExpectedResultCount">0</property>
    </testProperties>
  </test>
  <test name="PatientDiscovery-NoResults(25tx10r)" testcase="Nhin.PatientDiscovery" numberOfThreads="25" numberOfIteration="10">
    <testProperties filename="PatientDiscoveryLoadtest-soapui-project.properties">
      <property name="PatientDiscovery.Patient.GivenName">UNKNOWN</property>
      <property name="PatientDiscovery.Patient.FamilyName">UNKNOWN</property>
      <property name="PatientDiscovery.ExpectedResultCount">0</property>
    </testProperties>
  </test>
</tests>
